# Generated by Django 4.2.21 on 2025-05-31 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=50)),
                ('pais', models.CharField(choices=[('AR', 'Argentina'), ('BR', 'Brasil'), ('CL', 'Chile'), ('OT', 'Otro')], max_length=50)),
                ('sobre_mi', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='guias_fotos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=50)),
                ('pais', models.CharField(choices=[('AR', 'Argentina'), ('BR', 'Brasil'), ('CL', 'Chile'), ('OT', 'Otro')], max_length=50)),
                ('sobre_mi', models.TextField(blank=True)),
                ('moto', models.CharField(default='Sin, por ahora', max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='pilotos_avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('detalle', models.TextField()),
                ('fecha_salida', models.DateField()),
                ('cant_dias', models.PositiveIntegerField()),
                ('km', models.PositiveIntegerField()),
                ('dificultad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('max_pilotos', models.PositiveIntegerField()),
                ('fecha_update', models.DateTimeField(auto_now=True)),
                ('guia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viajes.guia')),
                ('pilotos', models.ManyToManyField(blank=True, to='viajes.piloto')),
            ],
        ),
    ]
