# Generated by Django 4.2.21 on 2025-05-31 13:24

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia',
            name='sobre_mi',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Sobre mí'),
        ),
        migrations.AlterField(
            model_name='piloto',
            name='sobre_mi',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Sobre mí'),
        ),
    ]
