# Generated by Django 4.2.21 on 2025-05-31 15:51

from django.db import migrations
#import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0002_alter_guia_sobre_mi_alter_piloto_sobre_mi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='detalle',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='detalle'),
        ),
    ]
