# Generated by Django 4.2.21 on 2025-06-01 11:49

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0003_alter_viaje_detalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guia',
            name='user',
        ),
        migrations.RemoveField(
            model_name='piloto',
            name='dni',
        ),
        migrations.AddField(
            model_name='guia',
            name='apellido',
            field=models.CharField(default='Guia', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guia',
            name='email',
            field=models.EmailField(default='mail@mail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guia',
            name='fecha_nac',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guia',
            name='nombre',
            field=models.CharField(default='nombre', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piloto',
            name='fecha_nac',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='piloto',
            name='moto',
            field=models.CharField(blank=True, default='Sin, por ahora', max_length=100),
        ),
        migrations.AlterField(
            model_name='piloto',
            name='sobre_mi',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Sobre mí'),
        ),
    ]
