# Generated by Django 4.2.21 on 2025-06-01 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0004_remove_guia_user_remove_piloto_dni_guia_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='guia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes', to='viajes.guia'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='pilotos',
            field=models.ManyToManyField(blank=True, related_name='viajes', to='viajes.piloto'),
        ),
    ]
