# Generated by Django 4.2.21 on 2025-06-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0005_alter_viaje_guia_alter_viaje_pilotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piloto',
            name='avatar',
            field=models.CharField(default='default.png', max_length=100),
        ),
    ]
