# Generated by Django 4.2.21 on 2025-06-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0006_alter_piloto_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia',
            name='sobre_mi',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='piloto',
            name='sobre_mi',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='nombre',
            field=models.TextField(max_length=100),
        ),
    ]
