# Generated by Django 4.2.21 on 2025-06-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0007_alter_guia_sobre_mi_alter_piloto_sobre_mi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='detalle',
            field=models.TextField(max_length=100),
        ),
    ]
