# Generated by Django 4.2.21 on 2025-06-06 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0008_alter_viaje_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
